### ISSUE TITLE
Add Junit report

### ISSUE THREAD

**Issue by nirtal85** [bats-core/bats-core#107]
Hi,
please add a junit report option,
as a flag to the run:
should be like `bats (test files/folder) --junit`

**Comment by jasonkarns** [comment]
TAP is a very common, cross-language test output format. Due to being a pseudo lingua-franca of test report outputs, there are dozens of converters from TAP to other formats. Simply piping the TAP output to other formats will get you junit output without any modification to bats.

For instance: https://github.com/aghassemi/tap-xunit 

As it stands, the current formatter could be shipped as a standalone TAP converter that just receives Bats' TAP output. Creating a separate bats-xunit project would be a fine repo for future inclusion in a potential bats-core github org. I just don't think it should necessarily be bundled within bats itself.

related upstream issue: https://github.com/sstephenson/bats/pull/161

**Comment by DarwinJS** [comment]
We use Gitlab CI and it has recently gained JUNIT test results import and display - but this is the only format it supports so far. (https://gitlab.com/gitlab-org/gitlab-ce/issues/17081)

Very interested in following where this goes.

**Comment by filmil** [comment]
I think it's valuable to produce jUnit output right here in bats:

- tap format does not allow reporting test runtimes.
- the converter at https://github.com/aghassemi/tap-xunit is broken.  It generates files that don't validate against the junit XSD. For example, it omits `time` attribute,which is required: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd#L127

**Comment by jakub-bochenski** [comment]
FTR there is no  JUnit Schema (XSD or otherwise). The XML format originates from Ant and there was no strict schema defined at the time.  
Windy Road Technology Pty. Limited, which you link to, has no authority to define the schema for it. It's only their opinion and it's not normative.

I still think a native JUnit report would be useful for sake of timing though.

**Comment by filmil** [comment]
> FTR there is no JUnit Schema (XSD or otherwise). The XML format originates from Ant and there was no strict schema defined at the time.
> Windy Road Technology Pty. Limited, which you link to, has no authority to define the schema for it. It's only their opinion and it's not normative.

True.  But either way, people do use timing information in their jUnit test results.

> I still think a native JUnit report would be useful for sake of timing though.
> Another reason is that installing node just to convert the output format seems excessive

I'm with you there.  However, in the end I rolled my own post-processor: https://github.com/filmil/tap2junit.  In the end I'm not a big fan of more bash. :)

**Comment by jakub-bochenski** [comment]
> I'm with you there. However, in the end I rolled my own post-processor: https://github.com/filmil/tap2junit. I'm not a big fan of more bash. :)

Nice. Unfortunately `go` is yet another dependency. 
Would you consider publishing this as a container to Dockerhub so that it can be used more easily (like `jq` or `shellcheck` etc.)?

**Comment by bmhm** [comment]
> Unfortunately `go` is yet another dependency.

It is not. Go is not an interpreted language. tap2junit is a binary.

**Comment by MatthiasScholzTW** [comment]
It seems this feature request is solved since the release of bats-core [1.2.1](https://github.com/bats-core/bats-core/releases/tag/v1.2.1) it is now possible to just run `bats --formatter junit ...`.

**Comment by martin-schulze-vireso** [comment]
> It seems this feature request is solved since the release of bats-core [1.2.1](https://github.com/bats-core/bats-core/releases/tag/v1.2.1) it is now possible to just run `bats --formatter junit ...`.

Theo Bulk of this Feature is done but details like the output and cli options have not settled yet.

**Comment by martin-schulze-vireso** [comment]
There is still some movement on the details but I think the issue here is done.
