### ISSUE TITLE
Missing data-provider feature

### ISSUE THREAD

**Issue by andras-tim** [bats-core/bats-core#135]
There use to be helpful if the `@test` supports any kind of data-providers.

**Comment by bvberkum** [comment]
This is whishlist item for me as well, and I have not seen any code out there to do this. I think the best for this issue to take a step back and implement Bats extension points first. While we document the exact format and file/suite structure which we all want official Bats to support (here on the wiki).

This is because a data provider feature can currently be easily implemented by hacking the bats-preprocess, ie. replacing it with a customized version. So maybe support for that is something to look at here. 

- adopt syntax or convention for Bats to declare dependencies
- possibly make bats resolve repo and install the deps, or react at least to non-supported feature
- have official or third-party provide extension in repo

OTOH extension points would be
- preproces
- format-tap-stream
- support libraries, installed for use with load

There is no convention wrt. dependencies or types of extensions. So that is why I bring all of this up.

You can write the above helper code and have the first Bats scriptline or setup do the initial git clone in a (hidden) dir and setup the env. Aside from the libexec scripts though (unless installed with basher or user has special privileges).

But ff bats resolves deps, then in the project or options I might want to allow or forbid certain repos. Bats has no rc or config, what are the opinions on that?

I personally would use some c-style preproc directive for a hacked setup. Ie. my preproc would handle like:
```
#depends 'vendor/repo'
setup() { true; }
@test "...." { true; }
```
 
That is not going anywhere near a data-provider, but when you look at the actual preprocess you only need to catch and rewrite every piece of ``@test ...`` and finally register all the new function names. The result is a bash script with slightly obtuse names and some boilerplate added in front of each test-routine.

So it would be easy to introduce build matrices and some kind of templating and data-provider feature right there, just by transforming your own format.

I'm drawing a blank how that would look like right now.  And there's probably quite a few incompatible opinions on that too. Sometimes you have a file or CSV, other times you may want to write your own outline+table syntax like Gherkin has.

By setting a standard for the minimum in bats-core we can allow for a nice ecosystem of misc. extensions to grow.  A case could be made to have Bats load a local output formatter as well I think. 

So I think there are several potential issues here to look at in their own ticket.
```
bats --override-preproc SCRIPT ...
bats --override-formatter SCRIPT ...
```
These first two may be fairly straightforward, and with those changes a consensus on a common format might not be that important as well. Left then is how to initialize Bats in these customized cases. Maybe there is a case for hooks at other points, I have not looked into this.
```
bats --helper=my_load_func
BATS_ALLOW_EXT=my bats --my-ext VAL ...
```

But beside that I think it should be up to a project team or their ops to decide what to support. And keep bats-core limited in scope and hopefully stable. Above scriptlines are just some doodles.

**Comment by martin-schulze-vireso** [comment]
I am closing this issue now. The discussion above is only tangentially related to the title and the suggested features in dotmpe's comment are better discussed in #517.
