### ISSUE TITLE
Implement shellcheck in CI

### ISSUE THREAD

**Issue by mbland** [bats-core/bats-core#14]
We should integrate https://github.com/koalaman/shellcheck in our CI process.

In the meanwhile, we can encourage the use of tools like https://github.com/vim-syntastic/syntastic, which has saved my life as a Vim user.

Fun fact: I haven't yet implemented shellcheck for mbland/go-script-bash yet because, last time I checked, it didn't recognize `.` as a valid function name character. (I should check again, and submit a PR if that still isn't the case.)

**Comment by edouard-lopez** [comment]
There is a branch with [bats support](https://github.com/koalaman/shellcheck/tree/bats) but it's lagging behind, also see [related issue](https://github.com/koalaman/shellcheck/issues/417).

**Comment by mbland** [comment]
Thanks @edouard-lopez! I'm definitely interested in digging into this when I get the time—unless someone beats me to it, of course.

**Comment by ELLIOTTCABLE** [comment]
Can we use `bats-preprocess` as an interim measure, as mentioned by @dougm?

**Comment by espoelstra** [comment]
Having shellcheck would be handy as I tripped over an issue it might have caught today.

I have bats-core plus a couple extensions in a test project and I decided to run `bats -r test/` where the first level is my tests and everything under `lib` is bats-core or the other extensions, but only bats-core seemed to have an issue running this way. I'm guessing part of the issue was having `test` in the name got it caught up by a regex.

`test/libs/bats/libexec/bats-core/bats-exec-test: line 216: printf: `': not a valid identifier`

This prompted me to run `shellcheck test/libs/bats/libexec/bats-core/bats-exec-test` which produced quite a bit more output than I expected.

`shellcheck bats-exec-test`

```
In bats-exec-test line 18:
    BATS_TEST_FILTER="$2"
    ^-- SC2034: BATS_TEST_FILTER appears unused. Verify it or export it.


In bats-exec-test line 61:
  source "${filename}"
  ^-- SC1090: Can't follow non-constant source. Use a directive to specify location.


In bats-exec-test line 70:
  IFS=$'\n' lines=($output)
            ^-- SC2034: lines appears unused. Verify it or export it.
                   ^-- SC2206: Quote to prevent word splitting, or split robustly with mapfile or read -a.


In bats-exec-test line 220:
  if [[ "$BASH_SOURCE" != "$1" ]]; then
         ^-- SC2128: Expanding an array without an index only gives the first element.


In bats-exec-test line 362:
    printf "bats: unknown test name \`%s'\n" "$BATS_TEST_NAME" >&2
                                         ^-- SC1117: Backslash is literal in "\n". Prefer explicit escaping: "\\n".


In bats-exec-test line 379:
  . bats-preprocess <<< "$(< "$BATS_TEST_FILENAME")"$'\n' > "$BATS_TEST_SOURCE"
  ^-- SC1091: Not following: bats-preprocess was not specified as input (see shellcheck -x).


In bats-exec-test line 419:
  source "$BATS_TEST_SOURCE"
  ^-- SC1090: Can't follow non-constant source. Use a directive to specify location.

```

**Comment by alexdesignworks** [comment]
We should not be waiting on Shellcheck to implement support for `.bats` parsing.

The core of this project is written in `bash` and shellcheck can already understand this and help us with better code maintenance, including running it in CI for all pull requests.

**Comment by edouard-lopez** [comment]
`bats` support has been added to `shellcheck` in january, see https://github.com/koalaman/shellcheck/pull/1469
