### ISSUE TITLE
What should be a failling test succeeds

### ISSUE THREAD

**Issue by whyvez** [bats-core/bats-core#148]
```
macOS 10.13.5
GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
Bats 1.1.0
```

script
```
#!/usr/bin/env bash

set -o errexit

one() {
  return 1
}

two() {
  return 0
}

three() {
  return 0
}

main() {
  one
  two
  three
}

[[ "${BASH_SOURCE[0]}" = "${0}" ]] && main "$@"
```

test
```

setup() {
  source ./script || true
}

@test "script" {
  run main

  [ "$status" -eq 0 ]
}
```

```
bats test
 ✓ script

1 test, 0 failures
```

I would expect this test to fail. Could you explain why it does succeed? If I return 1 from the three function it fails. I would expect that with `errexit` set it would fail with the first non-zero return. 

Where am I wrong in my assumptions?

**Comment by cdevinesr** [comment]
It is because you `source` the script, so your `set -o errexit` is functionally useless, as it is equivant to `set -e`, which is already set is BATS's execution context.  When `run` executes, part of what it does to ensure proper function is to `set +e` to let the script handle it's own options.

Your test *might* fail if you were to move your `set -o errexit` into your `main` function, because then it is set at execution time.

**Comment by mbland** [comment]
Good catch, @cdevinesr!

This is something to be aware of when sourcing files and then executing functions directly via `run`. If instead the test ran `./source` script itself:

```bash
$ cat test.bats 
@test "script" {
  run ./script

  [ "$status" -eq 0 ]
}

$ bats-core/bin/bats ./test.bats 
 ✗ script
   (in test file test.bats, line 4)
     `[ "$status" -eq 0 ]' failed

1 test, 1 failure
```

**Comment by whyvez** [comment]
> Your test might fail if you were to move your set -o errexit into your main function, because then it is set at execution time.

@cdevinesr That worked!
