### ISSUE TITLE
Command output gets globbed

### ISSUE THREAD

**Issue by vonbrand** [bats-core/bats-core#156]
Command output gets globbed, if it contains e.g. "*" it might not be as expected. The attached testfile fails test 1.
[tst-star.txt](https://github.com/bats-core/bats-core/files/2542573/tst-star.txt)

**Comment by vonbrand** [comment]
A patch (git style) with a new testcase. The result passes all existing tests AFAIKS.
[0001-Don-t-glob-output.patch.txt](https://github.com/bats-core/bats-core/files/2553288/0001-Don-t-glob-output.patch.txt) (can't upload a plain `.patch`...)

**Comment by mbland** [comment]
Thanks for the catch. Please submit this as a proper pull request after making two tweaks to the patch: combine the first two `set` lines as `set -f +eET`, and change the last line in `run()` from `set "-$origFlags"` to `set "+f -$origFlags"`.

I don't _think_ this will break existing usages. @jasonkarns @sublimino @cdevinesr @bvberkum Do you have any insights or concerns?

**Comment by cdevinesr** [comment]
The only thing I can imagine this breaking would be tests written where the globbing is intentional.  Would it perhaps be better to make the glob disable an optional argument to `run`?  This would allow the user to decide whether they want globbing in use or not.

Of course, if we do, that would leave us deciding which of the choices would be the default behavior.  Given how strange Bash can be with glob expansion and quotes overall, would it maybe be the most intuitive (particularly for newer Bash users) to default to disabling globbing, with the option to override that when `run` is invoked in tests?

**Comment by cdevinesr** [comment]
I'd also like to note that it looks like someone is already somewhat trying to tackle this with #152.

**Comment by mbland** [comment]
@cdevinesr #152 deals with globbing for `$output`. This deals with globbing for the command line to `run`.

**Comment by jasonkarns** [comment]
I haven't dug into this very deeply (or really at all) but  if glob patterns are wrapped in single quotes to `run`, won't that fix the issue? It seems like any other glob-sensitive invocation, wherein the caller can avoid or leverage globbing by how they pass the arguments...

**Comment by mbland** [comment]
I also haven't run it myself yet—the excuse being a long story that I'm just about to summarize on my blog—but I think what's happening is that the result of expanding `"$@"` in `run()` is then getting expanded again inside the command substitution of `output="$("$@" 2>&1)"`.

**Comment by cdevinesr** [comment]
@mbland Fair point.  I kinda skimmed it.

@jasonkarns Quoting the glob won't actually stop `run` from doing globbing, because the quotes are removed once `*` is passed in, and then the glob is processed as the command given to `run` is executed.  Surrounding it in two sets of quotes would probably fix that problem, but that solution isn't very clean.

**Comment by jasonkarns** [comment]
@cdevinesr 	ah right, i wasn't thinking that `run` would obviously need to invoke the thing "again"

**Comment by vonbrand** [comment]
It fails exactly the same way if the '*' isn't even visible to the `run` expansion.

**Comment by vonbrand** [comment]
Changed the patch as requested. Fixed the test to make the command run immune to shell mangling arguments.
Pull request pending.
