### ISSUE TITLE
Expands (or attempts to?) expressions in test names

### ISSUE THREAD

**Issue by jasonkarns** [bats-core/bats-core#161]
This is a regression of sorts, in that it differs from bats 0.4.0.

Example:

``` bats
@test 'foo `bar` baz' {
  true
}
```

In 0.4.0 the output is:

```
bats foo 
 ✓ foo `bar` baz

1 test, 0 failures
```

In 1.1.0 the output is:

```
npx bats foo 
 ✓ foo  baz

1 test, 0 failures
```

**Comment by bvberkum** [comment]
The 0.4.0 pre-processor preserved the quoting, v1 changed the match (to a pattern I don't really understand) and cleans up the match groups a bit.

Regardless of quotes this is the preprocessed bats
```sh
test_1-2e_foo_-60bar-60_baz() { bats_test_begin "1. foo `bar` baz" 1;
    true
}

test_2-2e_foo_-24-28bar-29_baz() { bats_test_begin "2. foo $(bar) baz" 5;
    true
}
```

What is also no longer possible, is utilizing the space after the test name. I have not used this yet, but only because the internal impl. did not make all of the arguments available to the test:

```bats
@test "This is a string for the test name" "This is another string" {
  true
}

@test "This is another test name" "Another string" "Etc." "Etc." {
  true
}

@test "This is another test name (II)" true {
  true
}

@test "This is another test name (III)" true 123 0.5 {
  true
}
```
But looking toward the future for Bats as a established shell-test framework, then this to me seems exactly one of the things that may be explored for features to make test writers happier. As well as looking at companions for ``@test``, I'm pondering 

There are other issue with the syntax as well, 

- name encoding is silly (``-5f`` for ``_``, etc.)
- no proper readline continuations because of ``read -r`` (also v0.4 and earlier). It cannot do this:
```
@test "This is my really \
  really \
  long test name" { ...
```

The previous preprocessor was able to run stand alone as well, the current requires some env exports from bats.

 @mbland Looking at the log for the ``preprocessor`` script I don't think reintroducing these behaviours should be a problem or conflict with the current intentions of the code:

- preserve quotes
- run standalone, or set some defaults or abort at least on undefined
- fix the matching so it has arguments again, and patch bats_test_begin as well so test writers can access these as data that is not part of the label/test-name

**Comment by jasonkarns** [comment]
Closing this as it seems this was added intentionally.

https://github.com/bats-core/bats-core/blob/5eb45c18a58ace003eb4c42ef097cc4d4eb2d819/test/bats.bats#L310-L314

https://github.com/bats-core/bats-core/commit/3ab495fda2e032b869eee86b262e651ff907c9c5

I'm not certain I _like_ the behavior, but it definitely adds more flexibility to authoring tests, so 👍 ?
