### ISSUE TITLE
Using bats-core with https://github.com/grayhemp/bats-mock and bats-assert

### ISSUE THREAD

**Issue by annawinkler** [bats-core/bats-core#167]
I installed bats via homebrew and I think that does not work with bats-mock and bats-assert being added as git submodules in my project. Is there a recommended way to use all three? I'd be happy to add the instructions for using git submodules for all three if that makes the most sense. Thanks!

**Comment by jasonkarns** [comment]
Did you install `bats` or `bats-core` from homebrew?

I can't speak to the use of grayhemp/bats-mock since that's a third-party library. Which bats-assert are you using? (I know there are many)

I personally have [bats-core](https://www.npmjs.com/package/bats), [bats-assert](https://github.com/jasonkarns/bats-assert-1), and [bats-support](https://github.com/jasonkarns/bats-support) installed as npm deps (the repos are node-related) and they all work together.

**Comment by annawinkler** [comment]
I installed `bats-core` via homebrew. My repo is bash scripts, so I think git submodules is a better way to go for my project. Thank you for posting the repos you have. I have these:
```
    git submodule add https://github.com/bats-core/bats-core test/libs/bats
    git submodule add https://github.com/jasonkarns/bats-assert-1 test/libs/bats-assert
    git submodule add https://github.com/grayhemp/bats-mock.git test/libs/bats-mock
    git submodule add https://github.com/ztombol/bats-support test/libs/bats-support
```

I'm going to close this issue as I think I'm on to my next issue 😄

**Comment by jasonkarns** [comment]
👍 

I agree that submodules are probably the right thing for a pure shell repo, though I might suggest subtrees instead: https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree (they have some benefits over submodules _if you don't intend to actually develop in the submodule_)

feel free to post other problems back on this issue.

**Comment by annawinkler** [comment]
Thank you for that suggestion - I have not used subtrees and will dig into that article.
