### ISSUE TITLE
How to check the value of an environment variable

### ISSUE THREAD

**Issue by annawinkler** [bats-core/bats-core#168]
I tried posting this question on gitter, but because of the message limit that felt ... slower. 

I have a test file where I use `load` to load the functions I am testing. I am mocking `function 1` because that function makes a `curl` call that I don't want to actually make. `function_two` calls `function 1` and uses the http codes to set an environment variable. I want to make sure the environment variable is set correctly based on different http code values.

I have a test method like this:
```
@test "test for 404 and env var value" {
  mock="$(mock_create)"
  mock_set_output "${mock}" "404"
  _FUNCTION_1="${mock}" run function_two
  assert_success
  assert_equal ${output} 404
  assert_equal false ${MY_ENV_VAR}
}
```

${MY_ENV_VAR} doesn't have a value though in this test. Any suggestions? Thanks!

**Comment by jasonkarns** [comment]
`run` runs its command in a subshell, so any mutations to the environment are lost when the subshell exits: https://github.com/bats-core/bats-core/blob/5eb45c18a58ace003eb4c42ef097cc4d4eb2d819/libexec/bats-core/bats-exec-test#L68

Short story is this _sounds_ like an invasion-of-privacy test smell: https://github.com/testdouble/test-smells/tree/master/smells/unrealistic/invasion-of-privacy

If that function isn't meant to be invoked directly _in production_, then it probably shouldn't be tested directly. It sounds like the pain you're feeling is because the tests are attempting to test implementation details that are only observable within the internals of the subject under test.

My recommendation would be to restructure the code under test such that the thing you want to assert would be observable in production use. (ie, what is the _impact_ of those env vars being changed? assuming this code would be executed and not sourced in production, these env var changes wouldn't be visible to the parent shell in production either.)

**Comment by annawinkler** [comment]
Thanks for your reply! That is a great resource & Justin Searls is one of my fav people 😸 

I think I'm struggling with how to mock calls to curl an endpoint I don't have access to when I run my tests locally (it's a Google Cloud metadata endpoint that only exists on a running instance).

The test subject is a method that will be called in production to get the value of a variable that is stored in Google metadata. I'm trying to mock out calling `curl metadata-endpoint` and the resulting HTTP status. If the variable is not in the metadata, the HTTP status is `404`, and in that case I want to return a default value instead of a `404`.

My test subject is more of an integration test so I want to mock the two method calls that function makes. I wonder if I would have more success with this library https://github.com/jasonkarns/bats-mock versus this one https://github.com/grayhemp/bats-mock for having two mocks in a single test?

**Comment by martin-schulze-vireso** [comment]
The original issue has been addressed already. I don't know if @jasonkarns can give some more insights on the latter questions.
