### ISSUE TITLE
setup and teardown run even for skipped tests

### ISSUE THREAD

**Issue by alexdesignworks** [bats-core/bats-core#174]
When test has `skip` at the very beginning, looks like the `setup` and `teardown` run anyway. 

Is this intentional behaviour? If so - can this be documented (I can submit a documentation PR once this behaviour is confirmed by the maintainers).

Thank you

**Comment by cyphar** [comment]
This is intentional behaviour -- there's no real way to know whether `skip` will be executed and so `setup` and `teardown` need to be run like with every other test (not to mention that some tests conditionally skip, so `setup` and `teardown` might be necessary to decide whether the test will be skipped in the first place).
