### ISSUE TITLE
1.0 bug fixes

### ISSUE THREAD

**Issue by jasonkarns** [bats-core/bats-core#20]
(transferring bugs list from sstephenson/bats#196)

- [ ] Empty output lines are missing from `${lines[@]}`.
    sstephenson/bats#89
    sstephenson/bats#90
    sstephenson/bats#92

    sstephenson/bats#90 has already been merged to master
- [x] Use POSIX compliant options with head for better compatibility (e.g. Busybox support).
    sstephenson/bats#163

    closed by #17
- [x] Incorrect TAP format for skipped tests.
    sstephenson/bats#141
    sstephenson/bats#142

    will be closed by #19 
- [x] `set -o nounset` breaks `bats-exec-test`.
    sstephenson/bats#171
- [x] `bats-preprocess` breaks when translating a `@test` line that uses tabs for white space, instead of plain spaces.
    sstephenson/bats#98
    sstephenson/bats#122
- [x] Bats failing on OS X 10.11.2.
    sstephenson/bats#140

**Comment by mbland** [comment]
Corresponding to each of the above:

* Actually, empty `output` lines _are_ still missing from `lines`. I've got a [split_bats_output_into_lines helper](https://github.com/mbland/go-script-bash/blob/v1.6.0/lib/bats/helpers#L282-L291) (and its [__split_bats_output_into_lines helper](https://github.com/mbland/go-script-bash/blob/v1.6.0/lib/bats/helpers#L415-L423) for speed reasons) that would be trivial to apply—but it would be a breaking change for a lot of tests. I'd vote for that to go into v1.0, with a corresponding `bats_strip_blank_lines` helper or other mechanism to help people migrate from the old behavior to the new.

* I've noticed test breakages on Alpine, which I believe would fall into the Busybox compatibility bucket, although #17 did resolve the one issue. I'll try taking a look at them momentarily.

* I'll be reviewing #19 shortly.

* Haven't looked at the `set -o nounset` issue closely yet. Some definite subtleties there.

* The whitespace solution from sstephenson/bats#122 should now apply to the definition of `BATS_TEST_PATTERN` in `libexec/bats`, but otherwise should just work.

* I'm pretty sure sstephenson/bats#140 was fixed by f5acd286129e3b68945a33da7d74ece82564ac57 from #8. I'm also pretty sure the issue was the one identified by @mstade in https://github.com/sstephenson/bats/issues/140#issuecomment-259004085, whereby `set -e` is in effect, and an error causes `$(bats-exec-test -c "$filename")` to evaluate to the empty string, resulting in the syntax error. The new code isn't susceptible to this.

**Comment by mbland** [comment]
Update on the Alpine/Busybox business: Per #16, the failures I saw were due to `ncurses` not being installed and `tput` being missing, not due to any further Busybox compatibility issues.

**Comment by mbland** [comment]
Just opened #23 to address the `bats-preprocess` tabs issue.

**Comment by mbland** [comment]
#26 addresses the `set -o nounset` issue.

**Comment by mbland** [comment]
#23 addresses the `bats-preprocess` breaks on tabs in `@test` lines issue.

So the last one is empty output lines missing from `${lines[@]}`. @jasonkarns I'm happy to start tackling this one (later this week/weekend, most likely), but I'm wondering if we'd consider this a new "feature" at this point, to be postponed. Of the six issues listed in this thread, the other five clearly were bugs, but this last one is debatable.

**Comment by jasonkarns** [comment]
I sorta agree. And depending on the solution would be most likely to introduce a breaking change... I'd like to see about tagging some releases with the bugs that have already been released and see if we're good to tag it 1.0!

**Comment by mbland** [comment]
@jasonkarns @btamayo How and when do y'all want to proceed? Should we ship what we've got? Do we want to get #9 in first? I'll have a little bandwidth this weekend to help [keep 'er movin'][].

[keep 'er movin']: http://manitowocminute.com/

**Comment by btamayo** [comment]
@mbland @jasonkarns Sorry, work has kept me very busy, but bandwidth has opened up again. _Phew_. 

I'm glad the project's buzzing! Just quickly scanned through this last issue and I think that backwards-compat for this release is top priority, and anything that will likely break that should be pushed. That way when people migrate from the fork point to this repo (0.4 to 1.0), it will be a seamless (theoretically) transition with no breaking behaviors. 

If we lean towards this idea for 1.0, we can more easily zap bugs introduced between sstephenson/bats@0.4 and bats-core/bats-core@1.0 (including gathering reports and test cases). It makes the transition easier for users as well and makes the demarcation more clear.

Also it gives us a handy way to test out distributing the new package and announcing changes/deprecations for the next major version! 

So yep, happy to ship what we got. :)

**Comment by mbland** [comment]
Per my comment in #16, we're set to release v1.0.0 soon without the empty lines in `${lines[@]}`. Closing.
