### ISSUE TITLE
Is there currently a way to fail on undefined variables? (set -u option)

### ISSUE THREAD

**Issue by pdietl** [bats-core/bats-core#213]
I was having some problems where I spelled a variable wrong and the test was silently passing anyway. Setting `set -u` at the top of a bats file doesn't seem to work. Is there a way to catch undefined variables in tests?

**Comment by tralston** [comment]
BATS files aren't executed straight through like a normal script, see [Bats Evaluation Process](https://github.com/bats-core/bats-core/wiki/Bats-Evaluation-Process) in the wiki. Any code outside of a function isn't guaranteed to be executed.
In your case, you can either:

- put `set -u` at the top of each function (and `set +u` at the end of each function)
- put `set -u` in the `setup()` and `set +u` in the `teardown()` functions

The second option is preferable, since you don't have to write it for every test function. However, it still requires you to write it once per test file.

**Comment by virgilwashere** [comment]
> The second option is preferable, since you don't have to write it for every test function. However, it still requires you to write it once per test file.

Or be `load`ing a `test_helper` that has `setup()` and `teardown()` in it.

**Comment by x-yuri** [comment]
And `set +u` doesn't seem to be needed since even in 2019 each test was supposedly executed in a separate process.

[a]: https://github.com/bats-core/bats-core/blob/v1.1.0/libexec/bats-core/bats-exec-suite#L59
