### ISSUE TITLE
--jobs documented on github but not in man page and not recognized

### ISSUE THREAD

**Issue by mslinn** [bats-core/bats-core#222]
```
$ bats --jobs 3 *.bats
Error: Bad command line option '-jobs'
Bats 1.1.0
Usage: bats [-c] [-r] [-p | -t] <test> [<test> ...]

$ bats -j 3 test/curriculum.bats
Error: Bad command line option '-j'
Bats 1.1.0
Usage: bats [-c] [-r] [-p | -t] <test> [<test> ...]
```

The help message does not mention the `-j` or `--jobs` option, and there is no mention in the man page either.

**Comment by rockandska** [comment]
If i'm not wrong, `--jobs` is only available on `master` branch and you surely installed the release version 1.1.0 where those changes was not merged at that time.

For bats-core maintainers: it will be handy to have `--version` report the commit instead the version if there is no tag present because I assume that the version reported by @mslinn is not the one he use.

Regards,

**Comment by sublimino** [comment]
thanks @rockandska - that is correct. We'll look at getting the correct version (and a `-dirty` version for dev) reported for the next version
