### ISSUE TITLE
Focusing tests

### ISSUE THREAD

**Issue by saschagrunert** [bats-core/bats-core#223]
It would be nice to be able to focus single tests with a dedicated syntax element, like `@ftest`. If a test focus is set, then the overall test suite should fail to avoid excluding tests in automated CI pipelines.

**Comment by martin-schulze-vireso** [comment]
As I see it, this proposal has two parts:

1. easily select a subset of tests to run (the focused tests)
2. avoid missing failures due to accidentally restricting tests locally or on CI

Part 1 is very similar to tagging (#529). Part 2 might be further broken down by usecases: A `git bisect` script might benefit from actually getting accurate results for the focused run, while the CI should never be restricted. This might even be true for general filtering of any kind.
