### ISSUE TITLE
misidentified failing line

### ISSUE THREAD

**Issue by stevenjswanson** [bats-core/bats-core#253]
I've found an instance where bats reports the failure on an incorrect line:

With this in `foo.bats`
```
@test "good" {
    function foo () {
	true;
	return 0;
    }
    #FOO=yes
    foo;
    ! [ -v FOO ]
}

@test "bad" {
    function foo () {
	true;
	return 0;
    }
    FOO=yes
    foo;
    ! [ -v FOO ]
}
```
I get: 

```
$ bats foo.bats | cat
1..2
ok 1 good
not ok 2 bad
# (from function `foo' in file foo.bats, line 15,
#  in test file foo.bats, line 18)
#   `foo;' failed
```
The `bad` test should fail, but the failure is on `! [ -v FOO ]` rather than `foo`.

I'm on `master` at commit `87b16eb8ec381beca7f05d028e4ad7cf3f647a0f`.

**Comment by kgroat** [comment]
For your test cases, if you move the `!` inside, it should start reporting the correct line.  Like:
```bats
[ ! -v FOO ]
```

(Also of note -- the `-v` expression [isn't actually POSIX compatible](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html#tag_20_128_05) and some implementations don't have it, like BSD-based OS's.  If you need your bats scripts to be portable, you may want to keep that in mind.  If you're always going to be running on the same OS, then feel free to ignore this little tangent)

That being said, I'm seeing a similar issue when I use `[[` for an assertion:
```bats
@test "why" {
  echo "this is not the bad line"
  [[ "this" =~ "is the bad line" ]]
}
```
The report shows:
```diff
 ✗ why
   (in test file test/shared_functions.bats, line 26)
     `echo "this is not the bad line"' failed
```

My best guess is that this is because both `!` and `[[` are bash builtins, while `[` is actually an executable (usually found at `/bin/[` or `/usr/bin/[` but given *priority* like it's a builtin).

**Comment by strager** [comment]
I encountered this issue as well. I am working on a fix right now.

**Comment by martin-schulze-vireso** [comment]
Fixed since the PR above has been merged. However, you should be aware that using `!` on any but the last command will effectively disable failure exits. See https://bats-core.readthedocs.io/en/stable/gotchas.html#my-negated-statement-e-g-true-does-not-fail-the-test-even-when-it-should
