### ISSUE TITLE
Unable to get working on Windows under Git Bash using included instructions (No such file or directory)

### ISSUE THREAD

**Issue by jameswilddev** [bats-core/bats-core#256]
After following [these](https://github.com/bats-core/bats-core#installing-bats-from-source-onto-windows-git-bash) instructions from the readme, then creating the following file:

```bash
@test "this should show up as a test" {
  run "echo something"
  assert_output "something2"
}
```

Then executing it:

```bash
bats test.bats
```

I see the following output:

```
$ bats test.bats
/c/Users/james/libexec/bats-core/bats-exec-suite: line 48: /dev/fd/62: No such file or directory

0 tests, 0 failures
```

These results are [mirrorred](https://travis-ci.org/jameswilddev/sdf/jobs/619206766#L154) in a project of mine running on Travis CI.  This exact same project works fine on macOS and Linux, so it seems to me that this is some form of incompatability with the Windows environment (though that Travis CI test isn't following the included instructions).

What am I doing wrong?

**Comment by jasonkarns** [comment]
I'm making guesses since I can't look into the source at the moment, but the reference to `/dev/fd` makes me wonder if mingw (the subsystem on which the git-bundled bash runs) supports arbitrary file descriptors...

[As mentioned in the readme](https://github.com/bats-core/bats-core/blob/master/README.md#file-descriptor-3-read-this-if-bats-hangs), bats uses FD3, so my suspicion is that mingw just simply doesn't support file descriptors other than 0, 1 and 2. (This is purely my initial gut speculation, but that's where I'd start)

**Comment by jameswilddev** [comment]
As stated this seems to be a limitation of MinGW on Windows.  I’ve reverted back to the previous release and that works well. Thanks!

**Comment by jasonkarns** [comment]
@jameswilddev would you mind sharing the version(s) that work and those that don't? while I don't think windows is _officially_ supported, if it did work in a previous release, perhaps we can restore it at some point.

**Comment by jameswilddev** [comment]
I'm finding that the 1.1.0 release works well.  Some of the tools I'm using (bats-assert, bats-support) don't handle error conditions well (you get these file descriptor errors rather than any details when a test fails) but it seems to be enough to ensure that the code works at least.

**Comment by ferrisnorth** [comment]
Same, I have reverted to 1.10 so that I can run it on win10
