### ISSUE TITLE
Pretty output without terminal escape sequences

### ISSUE THREAD

**Issue by elboulangero** [bats-core/bats-core#265]
The `--pretty` output of bats is only suitable for terminals, as it contains terminal escape sequences. It is not suitable to be saved to a file. Ie:

```
$ bats --pretty test.bats > output.txt
$ vi output.txt
----
^[[1G   addition using bc^[[K^[[171G1/2^[[2G^[[1G ✓ addition using bc^[[K
^[[0m^[[1G   addition using dc^[[K^[[171G2/2^[[2G^[[1G ✓ addition using dc^[[K
^[[0m
2 tests, 0 failures
```

I know that I can save the `--tap` output to a file, but then the tap output is not really friendly to human eyes.

What I'd like is to save the pretty output to a file, without the terminal escape sequences, just plain utf-8 text.

Is there a way to achieve that already?

Otherwise, would it make sense to add such feature in bats? Basically, disabling any terminal formatting when stdout is piped, or offering a `--human` option that does pretty output without terminal escape sequences?

**Comment by martin-schulze-vireso** [comment]
Right now, the output is not designed to be fed directly to the likes of `vi` and there is no switch for that. There are two main features: 

1. colorizing
2. interactive output (basically printing the test name as soon as it runs, then printing the tick/cross when it finished)

We might want to have a way of turning these features on/off individually but the current code is not really suitable for that.

**Comment by jasonk** [comment]
One of the things I like about TAP is that there are a *lot* of options available to format it to look nice.  Rather than adding things to bats to control what the standard pretty output looks like, I recommend saving it as TAP and then using something like one of these to format it however you like:

https://github.com/zoubin/tap-summary
https://github.com/substack/faucet
https://github.com/joeybaker/tap-simple
https://github.com/namuol/tap-difflet

Plus, if you don't like any of the TAP formatters, you can use https://github.com/tapjs/tap-mocha-reporter to use any Mocha reporter to format TAP output.

**Comment by elboulangero** [comment]
@jasonk Thanks for taking the time to put this list together!

I'm not really using bats anymore these days, but I'll remember to check those tools out next time I use bats.

Issue solved from my point of view, so I'm closing it. Thanks again!
