### ISSUE TITLE
Deprecating the focus on posix sh compatibility

### ISSUE THREAD

**Issue by ntnn** [bats-core/bats-core#28]
The maintainers of sstephenson/bats made it clear that they wanted to use as much posix as possible.

While this makes sense in some cases (and would entirely be possible), I think that it doesn't fit the projects' scope.

1. BATS stands for *bash* automated testing system
2. The codebase uses features such as `pipefail`, which are not part of the POSIX sh spec (and likely won't be for the near future)

A negligible point is the cost of the additional calls to external programs, as modern machines don't have a problem with those (`[` e.g. was an alias to `test` until recently in bash, instead of `=~` `grep` or `expr` have to be used).

In general bash is more friendly to develop and read as a posix compliant `test`, e.g., does not allow for compounds like `[ 1 -eq 0 || 0 -eq 0 ]`, which is a common construct to use.

I'd like a clear statement if this project intents to go full posix or full bash. I'd be fine with either way, but currently it is a mix.

**Comment by mbland** [comment]
I'm in the full-Bash camp when it comes to the implementation details and what we support in the test syntax. There's already tons of Bash-isms throughout the code that existed from the beginning (i.e. before my updates in #8), and #24 unlocks double-bracket capability.

That said, for whatever external programs we might employ, ensuring POSIX compatibility with _those_ would be good practice—eliminating the need for them altogether via an equivalent Bash function or script implementation would be even better, from a portability and (usually) performance point of view. See #9 and the [dup-warning-#9 branch](https://github.com/bats-core/bats-core/tree/dup-warning-%239) linked from it for an example.

So, FWIW, there's the beginning of a statement, but I'd like to hear other @bats-core/bats-core members (currently @btamayo and @jasonkarns) chime in as well.

**Comment by ntnn** [comment]
On that notion I'd like to link to the [tools reference](https://devmanual.gentoo.org/tools-reference/index.html) of the gentoo dev manual, it largely focuses on POSIX (if it doesn't it is usually marked, e.g. as it is for `find`) and a bit friendlier to navigate then the [OpenGroup Pubs](http://pubs.opengroup.org/onlinepubs/9699919799/).

**Comment by sublimino** [comment]
Great point @ntnn! I can venture an opinion: 

Full BASH for me too - and very rarely do I see projects on GitHub opt for `sh` over `bash` ([BigQuery is at hand](https://cloud.google.com/bigquery/public-data/github) should anybody wish to dis/prove that anecdote!). The syntax is more obvious and gotchas are (marginally) fewer. Regarding `pipefail` - I can not live without it, and it is sufficient reason for BASH over sh by itself, IMHO.

Agreed with @mbland on replacing dependencies with BASH scripting where possible.

**Comment by jasonkarns** [comment]
I also agree with going full Bash, primarily because:

> There's already tons of Bash-isms throughout the code that existed from the beginning 

Perhaps not in this thread, but I'd also like to officially set a minimum supported version of bash.

**Comment by mbland** [comment]
@jasonkarns 3.2.57(1)-release is my vote. Apparently Apple will never ship an OS X with a higher version, since, as I understand it, Bash 4.x switched to GPLv3. Of course, people can install a more recent Bash via Homebrew, but if possible, it'd be nice not to have to require that.

**Comment by ntnn** [comment]
I'd suggest not to support a range but the latest available on mac, the latest available on what microsoft built there (the subsystem) and the the latest bash version. Supporting and testing against specific releases is much easier than to support a range - something in an older minor of bash 4 might have been fixed and backported by apple to bash 3, so we'd have a bug opened for a version within this range we don't actually support.

This is a problem similar to the python 2/3 debate, where many projects go with the same solution.

**Comment by mbland** [comment]
@ntnn Yes, I like that idea as well. Effectively it's what I've been doing on mbland/go-script-bash there are some bugs I work around because they're not too difficult, and I do limit my implementation to v3 features (e.g. no v4 associative arrays), but for early 4.x series bugs, I typically don't bother.

Anywho, let's get concrete. I propose a list such as:

* 3.2.57(1)-release on macOS
* latest bleeding-edge Bash (e.g. installed via `brew install bash`)
* Whatever is the default in standard Travis images
  * I have hit bugs in the default Travis CI image that _isn't_ in either v3 or a later v.4 release that I've had to work around in mbland/go-script-bash.
  * If those images have a bug severe enough, we may propose workarounds or lobby Travis to update their image.
* Latest version for the following platforms:
  * Git for Windows Bash (MSYS2 based)
  * Windows Subsystem for Linux
  * Cygwin
  * MSYS2
* Latest version for these platforms, too, since I happen to have VMs set up already:
  * Alpine Linux (though the Docker image from #29) may cover this
  * Arch Linux
  * FreeBSD 10.x and 11.x

Of course, I propose these because I've already set them up for my own project. I'm open to dropping some or adding more, but let's start there. There are interesting differences between several of these platforms. I don't expect Bats will necessarily hit any of them as things stand now, but better to be safe than sorry. Longer term, if we do add any assertions or other utilities, we almost certainly will. (Fortunately, I think I've already discovered and worked around most, if not all of them. :smile:)

**Comment by ntnn** [comment]
I have a GoCD server that could be used to run the test suite on containers from the different distributions, including GH PRs etc.pp. to avoid travis config magic to run the all the versions from the different distros.

As for macOS/Windows - these would require windows slaves at least for GoCD (and here my PowerShell-fu would be just enough to automate the testing for Cygwin - not considering the licensing issues/cost). So bats would have to be tested against their respecitve bash versions outside of their environment, which isn't exactly ideal but the best solution as the only problem there would be to find a way to automatically grab the latest bash versions for those environments.

**Comment by btamayo** [comment]
Thanks for this, and @ntnn thanks for starting this discussion.

Re: POSIX. Agree on full Bash (up to 3.2) when possible, and fall back to POSIX conventions where Bash doesn't have them. Since `bash` is in the name, I don't think it's common that the test suite will be invoked as `sh` for any specific purpose. Still, the different ways that the users invoke and use bats is so broad that we'll still end up breaking some uses. But a few broken builds and runs is worth the trouble for a more explicitly defined structure. Segue into...

Unfortunately Apple will never ship past 3.2 which is kind of heartbreaking (at least for me!) especially since 4 introduces associative arrays. Thanks for that great list @mbland! Sounds good to me. 

Thoughts @ntnn @mbland @jasonkarns @sublimino? If no one opposes, I'll stamp it in the README that we officially will (do our best to) support builds of bash on that list.

**Comment by ntnn** [comment]
@btamayo Ye, but the wording should be clear that those are the aimed platforms/versions, as well as that it is only possible to ensure the quality on automatically testable platforms - i.e. those that can be used in a container or VM for continuous builds.

**Comment by btamayo** [comment]
@ntnn Yup. I'll add extra emphasis just in case people are unfamiliar with the nuances of containers. :)

**Comment by mbland** [comment]
Closed by #67.
