### ISSUE TITLE
realpath not available on MacOS

### ISSUE THREAD

**Issue by jkroepke** [bats-core/bats-core#307]
Hi,

since https://github.com/bats-core/bats-core/commit/433db67f0081de7f0924ca74fe4afced9df5cdfb bats-core is using the command realpath which is not available on MacOS.

While [travis](https://travis-ci.org/github/bats-core/bats-core/jobs/682808214) reports OK for MacOS running bats inside github actions on MacOS reports some "not found" error. I have the same behavior on my local machine, too.

But all test running fine: https://github.com/jkroepke/helm-secrets/runs/639356455#step:8:6

Exception: If bats-core available via git but not installed via `install.sh`, tests are not running:

```
% ./tests/bats/core/bin/bats -r tests/unit 
./tests/bats/core/bin/bats: line 34: realpath: command not found
./tests/bats/core/bin/bats: line 41: realpath: command not found
env: ./libexec/bats-core/bats: No such file or directory

% ls tests/bats/core/libexec/bats-core/bats
tests/bats/core/libexec/bats-core/bats
```

**Comment by sublimino** [comment]
Can you confirm that you have neither `greadlink` or `readlink` installed please @jkroepke?

@waterkip looks like `realpath` may not be available by default.

Could you both please provide some debug info:
- version information for your OS
- any extra tooling installed from Homebrew, Github etc? 

I don't have a Mac so have to rely on Travis, which for some reason doesn't seem to represent vanilla OSX... :facepalm:

**Comment by waterkip** [comment]
Seems like OSX doesn't really have much to go on, it doesn't matter which route you take, it will fail:

https://unix.stackexchange.com/questions/254241/get-absolute-path-of-file-os-x

If you install coreutils with homebrew one should be good to go. Or... Find some pure bash way to traversing all the paths just to get where you want to be. But I'd rather not, there are a multitude of tools for this, but MacOS doesn't have these by default.

Or depend on a pure shell implementation: https://github.com/mkropat/sh-realpath

**Comment by sublimino** [comment]
@waterkip thanks for another clear and thought-out response :pray: 

OK, it sounds like we can investigate falling all the way back to `sh-realpath` for environments that have none of the other tools, and look at unifying the two path resolution functions.

This will be interesting to test, as Travis doesn't represent the same environment. Perhaps a dedicated Travis build job that removes any readlink-y tools so as to force test of https://github.com/mkropat/sh-realpath

How does that sound @jkroepke @waterkip?

**Comment by waterkip** [comment]
If you are going to take the route of falling back to sh-realpath, I would move all in.

**Comment by jkroepke** [comment]
> I don't have a Mac so have to rely on Travis, which for some reason doesn't seem to represent vanilla OSX... 🤦

You could test this on MacOS runner from GitHub Actions.

**Comment by jkroepke** [comment]
Sound looks great.

An alternative to the sh-realpath: 
* https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac 

I don't know if this is mac only. But its way less code the sh-realpath.

**Comment by dimo414** [comment]
Is it perhaps worth backing out this change, and revisiting it once a more robust solution is designed? There are [other issues](https://github.com/bats-core/bats-core/pull/217#issuecomment-594751309) with the current implementation as well; if it's causing real breakages it seems like it's not ready yet.

**Comment by waterkip** [comment]
realpath is used when (g)readlink cannot be found - which is the issue we are seeing here.
So there would still be an issue with for MacOS if you revert the patch. The situation when reverting would count on only (g)readlink. I'm not sure how that solves the problem. 
If you have a Mac, feel free to revert the merge and report back. Due to other engagements I don't have time to look/investigate/figure out how we can tackle this in another way. Read, I'm not sure how to incorporate sh-realpath as an external dependency: submodule, just copy/paste the code into bats. Or something similar.

**Comment by ko1nksm** [comment]
I will create a PR using [this code](https://github.com/bats-core/bats-core/pull/217#issuecomment-596058853) later. Advantages over other implementations is POSIX compliant and not using neither `readlink` nor `realpath`. Compatibility with `readlink -f` and well tested.

**Comment by sublimino** [comment]
Sounds great @ko1nksm, thank you! Of note is that there are multiple places that `realpath` is used, if they can all be addressed by this change that would be excellent. Or if you'd like to start a draft PR with one of the target areas I can help to integrate with the rest of bats.

@waterkip good points. Without a dependency or module system I'm in favour of keeping it simple to get this bug fixed: bringing the relevant code into a subdirectory, adding front matter / head metadata pointing to the upstream hash and version, writing simple integration tests, and getting the change out to users to test ASAP.

**Comment by jasonkarns** [comment]
If we want to pull in another repo as  "dep", we can (and should) use git-subtree. All the benefits of having the content directly in the repo (no submodule headaches); with the added ability to fetch changes from an external repo if it changes upstream.

**Comment by ko1nksm** [comment]
Hi @jasonkarns, thank you for the good suggestions.

It is certainly a common solution. However, `readlink -f` function is an exception. If you want to include shell scripts as libraries or execute as external commands, You need the location of the main script that resolved the symlink (unless installed globally). Because it is on a relative path from the main script.

Therefore the `readlink -f` function should be included in the main script. (This is a reason why I chose [Creative Commons Zero v1.0 Universal](https://github.com/ko1nksm/readlinkf/blob/master/LICENSE) to avoid licensing issues.)

The solution to this problem is to use a build system like JavaScript world. I would like it in shell scripts world, but it goes far beyond the scope of this issue.
