### ISSUE TITLE
Special variable BATS_TEST_NUMBER is not behaving as documented

### ISSUE THREAD

**Issue by harleypig** [bats-core/bats-core#322]
The readme states

    $BATS_TEST_NUMBER is the (1-based) index of the current test case in the test file.

I was using this in a global setup function to print out the name of the file for each test file, once per call to the test file.

    ((BATS_TEST_NUMBER == 1)) && printf '# --- %s\n' "$(basename "$BATS_TEST_FILENAME")" >&3

I've just upgraded to 1.2.0 and now this is broken. Only the first file is printed and if I add a line that prints the number, it just counts up to the total number of tests.

    printf '# -- %d\n' "$BATS_TEST_NUMBER " >&3

Either this is a bug and needs to be fixed, or the readme updated.

**Comment by shadowspawn** [comment]
I just hit this change in behaviour when I tried running my tests using master branch compared with v1.1.0.

I was using the pattern from https://github.com/bats-core/bats-core/issues/39#issuecomment-377015447 to do setup and teardown work for the file. e.g.

```
setup() {
  if [[ "$BATS_TEST_NUMBER" -eq 1 ]]; then
    ...
  fi
}
```

I see we can now use `setup_file` and `teardown_file`, but a breaking change for existing code relying on the numbering.

**Comment by martin-schulze-vireso** [comment]
I ran a bisect and it seems the change was introduced in 17e2cf35ba4eb44a25f47f31f079809c0f111338. @cyphar Was this intentional? The commit message does not mention this and there are no tests, so I assume it was not.

**Comment by cyphar** [comment]
No it wasn't intentional, though thinking about a bit, I would argue that the original behaviour wasn't really expected either (if the idea of `BATS_TEST_NUMBER` is to tell you the order of tests being run) -- in fact it's probably due to the bats limitations that I removed in 17e2cf35ba4eb44a25f47f31f079809c0f111338 (that bats treated the test suite as being per-file rather than per-test).

We can change it back to avoid breaking back-compat, but there should probably some other `BATS` variable that represents the test order number (something like `BATS_ABSOLUTE_TEST_NUMBER`).
