### ISSUE TITLE
recursive with junit formatter

### ISSUE THREAD

**Issue by jeff-cook** [bats-core/bats-core#341]
When running recursive with junit formatter there are name conflicts with the reports that do not exist in other formats.

```
bats --recursive --formatter junit .
```

The report files are all created in one directory. 
The files are named based on the bats file name, however ignore the path to the bats file.
If there is 2 `test.bats` files in different directories there will only be one `TestReport-test.bats.xml` reports file.
Also within the report file the path is not used in the class name.

**Comment by martin-schulze-vireso** [comment]
I'd like to separate this from the recursive mode. The problem comes from duplicate filenames and can be triggered via

```
bats --formatter junit subfolder1/test.bats subfolder2/test.bats
```

as well.

When using one output file per input file, we would have to either put the whole path into the resulting file name or mirror the input folder structure from a given anchor, to avoid the name clashes between duplicate file names in different folders.

I had a look again at the JUnit xml schemes and noticed that the current output somewhat deviates. It uses `<testsuite>` as root node whereas all XSDs I found would put `<testsuites>` as root with mutliple `<testsuite>`s as children. If this format is compatible with the desired targets, I would propose to switch to a single file output, which would eliminate the problem.

**Comment by jeff-cook** [comment]
I would be good with creating a single xml file, or putting each xml file in the dir with the .bats file creating it.

Anything I can do to help?

**Comment by martin-schulze-vireso** [comment]
I think the single xml file is the easiest to implement.

> Anything I can do to help?

You could venture your own PR for this or help on review/test a PR that was done by someone else.
