### ISSUE TITLE
Run some code only once before any test (and probably other after)

### ISSUE THREAD

**Issue by BraisGabin** [bats-core/bats-core#39]
I'm writing some tests with bats to test my docker image.

All my tests depends on the same image so I have two options:

* Build the image before every test (using `setup()`). Docker use the cache and it is not that slow... but it's slower that do nothing. And the output is poluted.
* Remeber to run the `docker build` before I run bats... this is much faster but it force me to remeber to launch the `docker build` command EVERY time. At the end of the day this is even slower because I forgot to do it and I need to launch bats twice.

It'd be great to define two new functions and call them before and after all the tests run.

**Comment by BraisGabin** [comment]
I'm looking for something similar to [`@BeforeAll`](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/BeforeAll.html) in JUnit5 (`@BeforeClass` in JUnit4)

**Comment by andrewfowlie** [comment]
I agree that a global teardown and a global setup would be helpful.

**Comment by mbland** [comment]
I'm interested in this as well, possibly for 1.0.

**Comment by BraisGabin** [comment]
How could we call this two new methods? I did a little research:

|options|Once per file (before)|Once per test (before)|Once per test (after)|Once per file (after)|
|-----|-----|-----|-----|-----|
|bats|-|setup|teardown|-|
|Python|setUpClass|setUp|tearDown|tearDownClass|
|JUnit5|beforeAll|before|after|afterAll|
|node js|before|beforeEach|afterEach|after|

The most conservative way would be to use `setupFile` and `teardownFile` (similar to Python). But I think that the JUnit5 or node js names are easier to understand. Any thoughts about this?

**Comment by andrewfowlie** [comment]
Personally, I'd favour lowercase separated with underscores and don't find adding `file` to function name that informative. I'd favour e.g, `initial_setup` and `final_teardown`

**Comment by jsok** [comment]
I've implemented this behaviour in many projects and named the functions `{setup,teardown}_suite`.

That's consistent with the bats nomenclature right?

**Comment by extsoft** [comment]
I suppose the better names will be `before_all` and `after_all`. IMXO, these names will explain the functionality in the best way.

**Comment by szaydel** [comment]
I actually added this to address this need, but it is surely not the way to go. I think `before_all` and `after_all` would be good names and ideally be supported whether only a single file is being processed or a directory with one or more .bats files. What I have done here does not even work with single files.
```
diff --git c/libexec/bats w/libexec/bats
index 9dd32dc..de7dc1a 100755
--- c/libexec/bats
+++ w/libexec/bats
@@ -139,13 +139,18 @@ if [ "${#arguments[@]}" -eq 0 ]; then
 fi

 filenames=()
+suite_setup_file=
 for filename in "${arguments[@]}"; do
   expand_path "$filename" 'filename'

   if [ -d "$filename" ]; then
     shopt -s nullglob
     for suite_filename in "$filename"/*.bats; do
-      filenames["${#filenames[@]}"]="$suite_filename"
+      if [ "$suite_filename" == "setup.bats" ]; then
+        suite_setup_file="$filename/setup.bats"
+      else
+        filenames["${#filenames[@]}"]="$suite_filename"
+      fi
     done
     shopt -u nullglob
   else
@@ -160,6 +165,11 @@ else
 fi

 set -o pipefail execfail
+  # Setup suite first, if have suite setup file.
+  # This is probably not a good way to do implement a pre- hook.
+  if [ -n "$suite_setup_file" ]; then
+    suite_setup_file || exit 1
+  fi
 if [ -z "$pretty" ]; then
   exec "$command" $count_flag "${filenames[@]}"
 else
```

**Comment by BraisGabin** [comment]
A setup file for each dir can be useful but really difficult to manage. I think that the file level is easier to understand and more common in other test frameworks.

**Comment by vikin91** [comment]
Any PR with this function on the horizon?

**Comment by szaydel** [comment]
My feeling is this needs to be implemented differently from the hack job that I created. Mainly, I think there need to different handling rules, different from tests anyway, for these one-time setup/teardown things, because depending upon what you are testing, sometimes you pretty much expect at least some part of setup and some part of teardown to fail.

**Comment by bvberkum** [comment]
Having not done any code spelunking for this yet, but it is the next thing on my wishlist.

One nitpick in the issue definition, given the table by @BraisGabin I think 
>  "before and after all the tests"

should be more specific
> "at the start and end of each testfile".

And for clarity probably add 
> "before respectively after the per-test setup/teardown hooks". 

The steps should run the same way as a setup/teardown hook as far as possible.

This way we get Bats to handle any setup/teardown step combination whatever the suite without adding anything too much.

I'm a bit ambiguous on the naming, I would stay within Bats nomenclature:

`{setup,teardown}_once`

Avoid 'suite' because to Bats a suite is a run of test files, implying the steps are at the very start and end of the run which is not what I think we should aim for. Other suggestions seem to introduce new/foreign nomenclature:

`initial_setup/final_teardown`
`{before,after}_all`
`{setup,teardown}_suite`

I would be fine with the first maybe. Or the second but because I'm familiar with other test frameworks. I'm trying to match the name as faithfully as I can with the above specification.

**Comment by tterranigma** [comment]
Just to note, for those who need this functionality now, you can already achieve this by testing for the number of the test being executed. Eg:

```sh
setup() {
  if [[ "$BATS_TEST_NUMBER" -eq 1]]; then
    ...
  fi
}

teardown() {
  if [[ "${#BATS_TEST_NAMES[@]}" -eq "$BATS_TEST_NUMBER" ]]; then
    ...
  fi
}
```

**Comment by tterranigma** [comment]
Just noticed @bvberkum's comment:

> Avoid 'suite' because to Bats a suite is a run of test files, implying the steps are at the very start and end of the run which is not what I think we should aim for. 

Given the comment above, I 'm thinking that it would be extra code to implement in a different way what is already there. It is also more flexible to use the conditionals on the test number. For instance, imagine you want to run the setup for all tests but the first.

If you agree with the above, I would suggest that this issue discusses the possibility of a `suite_setup` and a `suite_teardown` function. 

In this case, I cannot think of a way other than having a specially named file containing the two functions that, if exists in the "suite directory", will get loaded. This would essentially lift the "burden" of having to write a wrapper script that surrounds the call to Bats with the suite setup and teardown tasks. To add a little more value to such a file, it could also act as an 'environment' file, so that the user can include variables that they need to be available in all test functions, enable strict mode, have custom functions or load custom libs, etc. It could even be name `environment`!

An extra bonus of the above approach is the flexibility it might provide in organizing test files. Imagine a hierarchy of directories each containing such a special file, with the top level file providing the common environment for all _subsuites_ and the n-level files overriding/adding to it.

The drawback of the approach would be that the flexibility above could prove messy. What happens if you run a test suite starting from one of the subdirectories? Does the n-level special file depend on the n-1 potential upper-level special files? Still this seems the kind of question the user has to answer all the time when developing their project.

**Comment by szaydel** [comment]
I thought I should try something like this, based on my experience with tests I created to this point and with intent to make change as minimal as possible.

There are several downsides to this approach. One is that it is still per file, so not really global, but I came to realize that I really want to have a per file setup and teardown logic. The other obvious one, because it is nothing more than an experiment, is lack of any error handling. I am going to experiment with this a bit before I invest any time into error handling, simply because it requires some thought, and I am not convinced this approach is best to begin with.

Maybe others can comment and perhaps this will raise a better solution in the process. I am not convinced this is a good way to do things, but it seems to work, and it seems to be reasonably simple, so far.

https://github.com/bats-core/bats-core/compare/master...szaydel:szaydel/setup-teardown

**Comment by annawinkler** [comment]
I would also be interested in a way to add setup and teardown before all the tests (e.g., like `before_all` and `after_all`).

**Comment by tterranigma** [comment]
BTW, my suggestion [above](#issuecomment-377015447) is not bulletproof as the `--filter` option that bats supports changes the number of tests. Using names (with `BATS_TEST_NAME` is more reliable.

**Comment by znerd** [comment]
Let me add a specific use case: I would like to have a `setup_once` (or `before_all` or whatever it ends up being called) function that will initialize the regular variables like `${lines}`, `${status}`, etc.

Rationale is that the `run` command I'm using is calling `docker`, and I'm testing the results from that invocation across a number of test functions. But since `docker` is a bit slow, now all my tests are slow, because the `docker` command is being executed on _each_ test function.

**Comment by martin-schulze-vireso** [comment]
https://github.com/bats-core/bats-core/issues/39#issuecomment-377015447
> you can already achieve this by testing for the number of the test

While it may be a corner case, when running tests interactively and aborting mid run the "suite" teardown will not be called correctly this way.

**Comment by jkroepke** [comment]
Any progress here?

**Comment by martin-schulze-vireso** [comment]
@jkroepke If you count #244 then there has been some progress on this.

**Comment by Pinjasaur** [comment]
Confused on the status of this. The README points towards `setup_file` and `teardown_file` being available when _not_ running in parallel mode but I'm not having any luck with those on v1.2.0 pulled from Homebrew locally. Any insight?

**Comment by martin-schulze-vireso** [comment]
@Pinjasaur It seems the documentation changes did not get pulled in correctly. They should work with parallel mode too, now. If they don't work as described in the documentation, could you please open an issue with a short reproducer?

**Comment by Pinjasaur** [comment]
Thanks @martin-schulze-vireso, I created a discrete issue for it: #318

**Comment by martin-schulze-vireso** [comment]
I am thinking about tackling the once per suite setup/teardown. Following problems come to mind:

1. It only differs for multifile suites, so all files should get the same suite_setup. How to avoid repeating the function per file -> move it into an extra file, e.g. bats_setup_suite.bash in the same folder.
2. if we don't run the suite, but only a list of files, we still need to run the suite setup, how do we achieve that? -> just search for bats_setup_suite.bash from the file's folder upwards

This comment is intended to draw some comments on the feasibility or possible problems with the envisioned approach.
