### ISSUE TITLE
Preprocessed files are removed despite --no-tempdir-cleanup

### ISSUE THREAD

**Issue by wvdvegt** [bats-core/bats-core#391]
I'm trying to see what causes all kind of errors in a load(ed) file. However there are no generated bash scripts when using the --no-tempdir-cleanup action. 

Any suggestions of how to obtain a generated scitpt from a bats file?

**Comment by martin-schulze-vireso** [comment]
Which version of bats are you using? What are you seeing exactly?

`--no-tempdir-cleanup` is only available from version v1.2.1 and above. When it is specified, each bats run should leave behind a folder like `/tmp/bats-run-<PID>/`.

> Any suggestions of how to obtain a generated scitpt from a bats file?

I suppose you mean the preprocessed .bats file? These are cleaned up in an extra step. There is currently no option to not remove them, but you can comment out the call to `bats_cleanup_preprocessed_source` in `bats-exec-file`. However, this won't be of much use to you. The files look nearly the same as the originals, just with some internal code appended and all `@test` markers replaced by functions.

The most likely cause is a failure before bats it gets to run anyhing, because of a malformed filed that is being sourced/loaded. 

Please provide an example that exhibits the problem, so we can work on improving diagnostics.

**Comment by wvdvegt** [comment]
I'm using v1.2.1

Can you add it to your todo list to keep this preprocessed script (for debugging purposes). 

It's related to my other issue #390 posted. As i cannot see the generated code i can't see where it goes wrong. 

I assume this script does not become stand-alone bash script (so i could run it using bash without bats installed).

**Comment by martin-schulze-vireso** [comment]
I think it is worth thinking about preserving the preprocessed files. @sublimino @cyphar Do you think an extra option is warranted or should we just remove the `bats_cleanup_preprocessed_source` call and let the tempdir cleanup do its job (or not)?

**Comment by sublimino** [comment]
> should we...let the tempdir cleanup do its job (or not)?
Agreed with this, I found tempdir cleanup confusing last time I used it.

I think `--no-tempdir-cleanup` should avoid cleaning ANY tmpdir from a run, in my mind it's a debug-only flag.

IIRC there was a potential problem with reused PIDs (although PID count is now billions on new kernels), so perhaps the directory should be explicitly cleaned at the start of a run in case of collision (if it's not already).

**Comment by martin-schulze-vireso** [comment]
> > should we...let the tempdir cleanup do its job (or not)?
> 
> Agreed with this, I found tempdir cleanup confusing last time I used it.
> 
> I think `--no-tempdir-cleanup` should avoid cleaning ANY tmpdir from a run, in my mind it's a debug-only flag.

Yes, I see ist the same way. 

> IIRC there was a potential problem with reused PIDs (although PID count is now billions on new kernels), so perhaps the directory should be explicitly cleaned at the start of a run in case of collision (if it's not already).

There is an explicit abort on existance of the tmp run directory, so this should be safe. However, it is not under test.
