### ISSUE TITLE
Printing in setup() is broken in --pretty mode

### ISSUE THREAD

**Issue by julianKatz** [bats-core/bats-core#425]
With the following `test.bats` file:

```shell
#!/bin/bash

setup() {
  printf "setup function\n" >&3
}

@test "The name of the test" {
  true
}
```

I get the following output:
```
❯ bats -p ./test.bats
 setup functionthe test                                                                                            1/1
 ✓ The name of the test

1 test, 0 failures
```

Note how "The name of the test" is being smushed together with the "setup_function" output.

This does not happen in `--tap` mode, where the output is:

```
❯ bats -t ./test.bats
1..1
setup function
ok 1 The name of the test
```

**Comment by martin-schulze-vireso** [comment]
When you print to FD 3 you have to make sure that you are generating valid TAP. So you should probably prefix those printfs by `# `.

However, that will still lead to this output, which is due to the "interactive" output of pretty mode, which will first print the running test name and then the tick symbol once it is finished. When you print to FD 3 during setup or the test itself, the text will interfere with the formatting by moving to the next line.

Why exactly do you want to print to FD3 instead of just stdout/err?

**Comment by martin-schulze-vireso** [comment]
Since you are talking about failures I don't really see the need for FD 3, since failures will emit the stdout/err output anyways. Emitting output early should only be important when the test hangs or you want live feedback.

The logging sounds like you want to see output/progress. Are you looking for a trace feature like #136?

**Comment by julianKatz** [comment]
Thanks for addressing this!!

Looking forward to the next release to try it out 💯
