### ISSUE TITLE
'bats -j N tests' hangs

### ISSUE THREAD

**Issue by yurivict** [bats-core/bats-core#446]
It runs without -j N but hangs with it.

bats-core-1.3.0
parallel-20210422
FreeBSD 13

**Comment by martin-schulze-vireso** [comment]
FreeBSD is not in our test set. Could you provide a minimal example where this occurs, so we can reproduce it?

Also, what happens when you specify --no-parallelize-within-files?

**Comment by yurivict** [comment]
Example from README is a testcase.

With ```--no-parallelize-within-files``` it doesn't hang, printouts from all tasks appear simultaneously in the end.

**Comment by martin-schulze-vireso** [comment]
There is an internal semaphore implementation that relies on flock, maybe the FreeBSD version works slightly differently.

**Comment by martin-schulze-vireso** [comment]
@jjg-dressipi Thanks for the pointer, but we don'- upgrade the locks so I don't think this is related. @yurivict I got around to trying this on a FreeBSD VM and could reproduce it there. Then I did `pkg install flock` and the issue was gone. Can you check whether your system has `flock` installed?

I must admit that the current code should inform better about the absence of flock but I am also confused why this did not result in an error message.

**Comment by yurivict** [comment]
Yes, installing the ```flock``` packages fixes this failure.
