### ISSUE TITLE
Print the time of each test and the complete suite

### ISSUE THREAD

**Issue by BraisGabin** [bats-core/bats-core#49]
The tests must be fast. This way the developers will run tests more often and the bugs will decrease.

Print the time of each tests and the time of the complete suite helps to find the slow tests and fix them.

**Comment by tterranigma** [comment]
I would like this functionality but behind a flag, eg `-b | --benchmark`.

**Comment by gnikonorov** [comment]
If this is still up for grabs, I would like to implement this feature.

**Comment by jasonkarns** [comment]
I'm probably 👍 on this as well. Though I might suggest `-p | --profile` which could be further enhanced to take numeric argument to print out the N slowest tests. prior art: https://relishapp.com/rspec/rspec-core/v/3-7/docs/configuration/profile-examples

To be clear, I'm suggesting the initial feature just print time per test as the original poster suggests, but the `-p` would more naturally lead to the additional profiling output.

**Comment by gnikonorov** [comment]
Thanks @jasonkarns, I'll work on this over the next few days.

**Comment by mbland** [comment]
The tricky thing with capturing the timing is that I don't know of a way off the top of my head to grab the output of `time` without creating a subshell, in order to report individual test case timing. We try to keep subshells to a minimum for performance reasons, which has an outsized effect on Windows platforms in particualr. So just keep that constraint in mind as you start wrestling with the problem.

And another thought to keep in mind: If there are a couple of slow tests dragging down the entire time of the suite, it's probably going to be obvious which ones they are. On the other hand, there's value in having the timing of the entire suite, to see if specific optimizations produce gains across the board (which is why I run `time bats` all the time).

It'd still be nice to have a switch to have Bats itself run `time` for the entire suite (since we hit complications running `time bats` in #116), which might be an easier first problem to solve.

**Comment by gnikonorov** [comment]
Thank you for the background @mbland, I'll look for an efficient way to solve this.

**Comment by gnikonorov** [comment]
Sorry for the delay on this, I've been caught up with a few other things. I'm polishing up a solution to timing of the entire suite without the `time` command ( to avoid subshells ) now.

**Comment by gnikonorov** [comment]
@mbland - I am not that familiar with `TAP` format. Would we want to suppress this functionality if we are printing out in `TAP` format? Or is it valid to include under `TAP` format as well.

**Comment by cdevinesr** [comment]
TAP has support for comments.  Timing information can be included in TAP output if the line begins with `#`.

**Comment by gnikonorov** [comment]
Thank you @cdevinesr !

**Comment by martin-schulze-vireso** [comment]
This has been implemented as part of the junit output and refined with #337. You just need to add `-T` to the bats command line to get the test timings in tap or pretty format.
