### ISSUE TITLE
Mac OS X and System Integrity Protection (SIP)

### ISSUE THREAD

**Issue by spinicist** [bats-core/bats-core#61]
Hi,

I'd like to report an odd issue using BATS on recent Mac OS X versions. When Apple added System Integrity Protection (SIP), an odd "feature" is that child processes no longer receive environment variables related to shared libraries, e.g. `DYLIB_LIBRARY_PATH`. This apparently has been known for a few years - https://www.postgresql.org/message-id/561E73AB.8060800@gmx.net.

This caused me a big headache this evening, because I swapped to building my suite of tools with shared libraries, and while developing I install them a subdirectory in `$HOME`. My environment has `DYLIB_LIBRARY_PATH` correctly set.

Sadly, with this set up BATS does not work, because the sub-shells spawned by BATS do not pick up the `DYLIB_LIBRARY_PATH` variable. I have resorted to hard-coding an `export` statement in my tests for the moments as a workaround. An alternative is to install my tools to `/usr/local`, which Mac OS will search for shared libraries by default.

If anyone has any suggestions for a better way round this, then I am all ears.

**Comment by mbland** [comment]
This is the first I've heard of this; thanks for bringing it to our attention. That said, generally I'd recommend having a dedicated test script in your project that sets your environment exactly as needed. I'd be afraid of having Bats automatically detect and work around this, since I can imagine a script developer who isn't aware of this Bats "feature" tell a hapless user who isn't aware of the `DYLIB_LIBRARY_PATH` "feature" that "it works on my machine!"

That said, I'm open to hearing from other bats-core maintainers and others. It may also be something worth noting in our documentation somewhere, though I'm not sure where.

**Comment by spinicist** [comment]
I agree completely - I opened this issue mainly as a note to anyone in the future who might experience this problem.

I have decided the easiest thing to do is add the following to a script that is included in all my BATS tests:
```
if [[ $OSTYPE == darwin* ]]; then
    # Work around SIP removing DYLD_LIBRARY_PATH in child processes
    if [ -e $HOME/.bashrc ]; then
        source $HOME/.bashrc
    elif [ -e $HOME/.bash_profile ]; then
        source $HOME/.bash_profile
    fi
fi
```

Ultimately I'd like others to be able to run my tests without too much fuss, I think this ought to work.
Thanks!

**Comment by AnneTheAgile** [comment]
FYI, to get my profile to run on my scripts, I put login on the top line. 
Either; 
````
#!/bin/bash -l
````
or;
````
#!/bin/bash --login
````

**Comment by spinicist** [comment]
How would I do that within a `.bats` file? I did think these were supposed to have a shebang at the top of the file?

**Comment by martin-schulze-vireso** [comment]
Seeing that this did not garner much attention, is not really a bats problem, and there is a workaround, I am closing this.
