### ISSUE TITLE
No error reported when both `setup_file` and `teardown_file` fail

### ISSUE THREAD

**Issue by jbriales** [bats-core/bats-core#615]
**Describe the bug**
When there is an error happening both inside `setup_file` and `teardown_file`, there will be no error reported.

Instead, it will print a message like this, with no pointers to errors:
```
   bats warning: Executed 0 instead of expected 1 tests

1 test, 0 failures, 1 not run
```

**To Reproduce**
Save into file and bats-run the tests below:
```sh
load /usr/local/lib/bats-support/load.bash
load /usr/local/lib/bats-assert/load.bash

@test "bats prints error in setup_file" {
  cat <<EOF >foo.bats
setup_file (){ false; }
$(echo @test) "foo" { true; }
EOF

  run bats foo.bats
  assert_output --regexp 'setup_file.*failed'
}

@test "bats prints error in teardown_file" {
  cat <<EOF >foo.bats
teardown_file (){ false; }
$(echo @test) "foo" { true; }
EOF

  run bats foo.bats
  assert_output --regexp 'teardown_file.*failed'
}

# Currently broken, no 'failed' message reported:
@test "bats prints error in both setup_file and teardown_file" {
  cat <<EOF >foo.bats
setup_file (){ false; }
teardown_file (){ false; }
$(echo @test) "foo" { true; }
EOF

  run bats foo.bats
  assert_output --regexp 'failed'
}
```

**Expected behavior**
A meaningful error message is returned,
akin to:
```
 ✗ setup_file failed
   (from function `setup_file' in test file foo.bats, line 1)
     `setup_file (){ false; }' failed

1 test, 1 failure
```

**Environment (please complete the following information):**
 - Bats Version: tried 1.5 and 1.7
 - OS: Fedora
 - Bash version: GNU bash, version 5.0.17(1)-release (x86_64-redhat-linux-gnu)

**Comment by martin-schulze-vireso** [comment]
The problem with this is that we are already in the exit trap due to the failed command in `setup_file`. When we encounter the failed command in `teardown_file`, the `errexit` can only terminate on the spot instead of recursing into another exit trap, thus skipping our output code.

Fixing this to your expected format would likely require to disable errexit on `teardown_file`. Optionally: only if we came from a `setup_file` failure?

While invastigating this deeper, I noticed that `teardown` is a bit ambiguous about its error behavior depending on where exactly the error happened, see #616. We probably should strive for unified behavior between all `function teardown*` to satisfy the least confusion principle.
