### ISSUE TITLE
fastfail should be enabled for subshell in run help function

### ISSUE THREAD

**Issue by joelee2012** [bats-core/bats-core#69]
consider following test case:
```bash
#test_fastfail.bats
1 setup() {
2   source fastfail.sh
3 }
4
5 @test "fast fail" {
6   run fastfail
7   [ $status -eq 0 ]
8 }
# fastfail.sh 
1 function fastfail {
2   ls notexist
3   echo done
4 }
$ bats fastfall.bats
 ✓ fast fail

1 test, 0 failures
```
the problem is in function run, fastfail should be enable for subshell like:
```bash
 50 run() {
......
 58   output="$(set -e; "$@" 2>&1)"

**Comment by mbland** [comment]
The disabling of fastfail by `run()` is a feature, not a bug. It's up to the code under test to set the flag if that's the desired behavior of that code; it's why `run()` disables it by default. In other words, `fastfail()` should set `set -e`.

**Comment by joelee2012** [comment]
is it possible to add a switch for this ? as for hundreds of functions to be tested, add ```set -e``` in every function is duplicated effort.

**Comment by mbland** [comment]
Possible, yes; desirable, no, as this seems a specialized use case (it sounds like this would be for a library of functions that expect `set -e` to be set instead of checking command outcomes and returning manually?) and it would complicate the framework when a reasonable workaround is available.

The workaround being, you can have a `fastfail-helper` script:

```bash
#! /usr/bin/env bash
set -e
source fastfail.sh
"$@"
```

Then your test would become:

```bash
@test "fast fail" {
  run fastfail-helper fastfail
  [ $status -eq 0 ]
}
```
