### ISSUE TITLE
Add on_failure callback

### ISSUE THREAD

**Issue by martin-schulze-vireso** [bats-core/bats-core#756]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to react to test failures in a specific way, doing special cleanup, inspecting in an interactive shell, ... currently, we can only use `teardown` and check whether the test completed.

**Describe the solution you'd like**
An `on_failure` callback function that gets called immediately, when the test is known to have failed. As a bonus this might allow for overriding the failure.

**Describe alternatives you've considered**
Special "failure only" cleanup can be done in `teardown` but is a bit more cumbersome. Dropping into an interactive shell could be solved with a specialized flag.

**Comment by wainersm** [comment]
Hi @martin-schulze-vireso ! As we talked in Gitter today, on [kata-containers](https//github.com/kata-containers/kata-containers) project we ran into a situation where this feature will be very useful.

As for """As a bonus this might allow for overriding the failure""", this is another feature very welcomed. Sometimes we know tests are failing and we want to keep them running instead of skipping, but we don't want the CI pipelines failing.
