### ISSUE TITLE
Hosting setup-bats github action

### ISSUE THREAD

**Issue by carlossg** [bats-core/bats-core#828]
**Is your feature request related to a problem? Please describe.**

https://github.com/mig4/setup-bats is a github action to install bats and has been abandoned for a while (2y) and would be good to host it under the bats-core org. 
https://github.com/mig4/setup-bats/pull/379 

**Describe the solution you'd like**
I'm willing to maintain it but would also benefit from other contributors to ensure continuity

**Describe alternatives you've considered**
Another fork under somebody's personal account but that could face similar problems in the future

**Additional context**

**Comment by brokenpip3** [comment]
I made one with both bats binary and all the bats libs: https://github.com/brokenpip3/setup-bats-libs

**Comment by martin-schulze-vireso** [comment]
To be honest I am a bit out of my depth (and out of time to change that) to assess these repos. For the wider Bats ecosystem it makes sense to have a well maintained, officially condoned action.

If you (both) can hash out which repository to use, we can certainly find a way to incorporate it into the org. I believe it would be a win win when you prove yourself as contributor here @carlossg to become a maintainer, in the long run reducing our "staff" shortage. :smile:

**Comment by brokenpip3** [comment]
If my actions looks good for both of you I can move it under the bats-org umbrella and keep maintaining it like I do right now

**Comment by carlossg** [comment]
I have tested @brokenpip3 action and it works, so having it under the bats-core org would be great and we could point other users here

**Comment by martin-schulze-vireso** [comment]
That sounds like an agreement. Could you do a code review @carlossg before we integrate the repo?
@brokenpip3 do you need help with the migration?

**Comment by brokenpip3** [comment]
Nope, seems my action is published in the github marketplace to avoid disruptions for the current users I will fork it inside the bats-org umbrella instead of moving it, that's all, I will do it in this week, just need to curve some time to do everything properly (may need to change some minors stuffs like testing, README etc)

**Comment by brokenpip3** [comment]
I forked the repo and add the necessary changes: https://github.com/bats-core/setup-bats-libs

@martin-schulze-vireso I need your help to accept the github da so we can publish the action into the github marketplace, thanks :) 


![image](https://github.com/bats-core/bats-core/assets/40476330/ed3062dd-491b-4e69-9403-aebb304929ef)

**Comment by martin-schulze-vireso** [comment]
I accepted the DA, so you should be good to go.

**Comment by brokenpip3** [comment]
Due to the unique name constraint I renamed the action from `setup-bats-libs` to `bats-action` and publish it in the github marketplace, you can find it [here](https://github.com/marketplace/actions/setup-bats-and-bats-libraries).
I also added a branch protection rule for the main branch and I will archive my own action.

![image](https://github.com/bats-core/bats-core/assets/40476330/c957b0e2-8f05-4eaa-96ff-4c661583e253)

**Comment by brokenpip3** [comment]
> I will archive my own action.

Done, @carlossg are you satisfied? can you try the again the action, this time under the bats umbrella? 
so we can close the issue, thanks :pray:

**Comment by carlossg** [comment]
looks good, thanks!
