### ISSUE TITLE
Add a flag to find tests in a directory recursively

### ISSUE THREAD

**Issue by alkhimey** [bats-core/bats-core#84]
This is a feature request.

Same as running all `.bats` files in a directory, but when `-r` flag is provided, tests will be discovered in sub directories as well (recursively).

**Comment by jasonkarns** [comment]
Does passing globs on the command line work?

`bats test/**/*.bats`

**Comment by mbland** [comment]
@jasonkarns `globstar` isn't available on the 3.2.57(1)-release on macOS.

The implementation in #109 seems reasonable, modulo the Windows problem (I'm looking into it locally). While I'm of the mind that doing a `bats $(find tests/ -name '*.bats' | sort)` is easy enough, being able to do `bats -r tests` removes that tiny bit of friction with minimum complexity.

Thoughts, @bats-core/bats-core?

**Comment by jasonkarns** [comment]
> isn't available on the 3.2.57(1)-release on macOS

rawr

Separate thought: a lot of other tools (and by a lot, I'm thinking mostly of test tools in the node world, but I'm betting rspec et. al. do it as well) accept a glob themselves. So instead of having a boolean recurse/no-recurse flag that operates on a directory, the CLI takes in a list of patterns that it globs itself.

So `bats 'test/**/*.bats'`. I'm _betting_ this may not be trivial since we can't just pull in a globbing library. But I'm throwing it out there as an idea, anyway.

I think it would lead to a cleaner UI where you just provide a list of files (globbed by the shell) or a list of patterns (globbed by bats). That would implicitly support running, say, two subdirectories or a discrete set of files. But would require some clever way of expanding the glob pattern ourselves...

**Comment by mbland** [comment]
> So bats `test/**/*.bats`. I'm betting this may not be trivial since we can't just pull in a globbing library. But I'm throwing it out there as an idea, anyway.
>
> I think it would lead to a cleaner UI where you just provide a list of files (globbed by the shell) or a list of patterns (globbed by bats). That would implicitly support running, say, two subdirectories or a discrete subset of files. But would require some clever way of expanding the glob pattern ourselves...

Right. As much as I love avoiding subshells, subprocesses, and pipelines, the `find | sort` approach cuts the Gordian knot here. Thankfully it isn't in a tight loop and happens only at Bats startup, so the cost is relatively minimal. Plus, the `-r` switch does adhere to the convention established by `cp` and `grep`, for example.

Hence, I'm inclined to merge #109, but will wait for a second approval. (Or you can go ahead and merge it if you're OK with it @jasonkarns; I've already approved the review.)

**Comment by jasonkarns** [comment]
> Feels like a tiny footgun

It's totally a footgun. 😄 Though usually, the gun seems pointed the other way 'round. The number of times I've seen people forget to quote their glob in npm scripts, and suddenly their script fails on CI or whatever env doesn't have globstar enabled, and they have no idea that locally it's expanding _before_ going to the utility (since they typically just expect the utility to be expanding the glob itself...)

But yeah, absent better options, I'm 👍 on `-r`.
