### ISSUE TITLE
`bats-preprocess: command not found` in bats 1.11.0-rc1

### ISSUE THREAD

**Issue by gioele** [bats-core/bats-core#858]
**Describe the bug**

ruby-build's tests fail when run with bats 1.11.0-rc1

```
 24s autopkgtest [19:14:20]: test command1: [-----------------------
 24s /usr/lib/bats-core/preprocessing.bash: line 12: bats-preprocess: command not found
 24s 1..1
 24s not ok 1 bats-gather-tests
 24s # (in test file test/build.bats, line 26)
 24s #   `tarball "$@"' failed with status 127
 25s autopkgtest [19:14:21]: test command1: -----------------------]
```

https://ci.debian.net/packages/r/ruby-build/unstable/amd64/42695794/

**To Reproduce**

1. Check out https://salsa.debian.org/ruby-team/ruby-build/
2. Run `bats tests/`

**Expected behavior**

The tests should run without any internal bats error.

**Environment (please complete the following information):**

 - Bats version: 1.11.0-rc1
 - operating system (including version): Debian unstable+experimental
 - `bash --version`: 5.2.21
 - Install method: Debian package

**Comment by brokenpip3** [comment]
can you post the same test with the trace (`-x`) option?

**Comment by martin-schulze-vireso** [comment]
After investigating a bit it seems like there might be interference due to the path changes which are done [here](https://salsa.debian.org/ruby-team/ruby-build/-/blob/master/test/test_helper.bash?ref_type=heads#L8).

The problem only exists when there are multiple files in the suite and the PATH is changed. Preprocessing the second file will fail because the PATH has been changed and does not contain `libexec/bats-core` (which contains `bats-preprocess`) anymore.

I believe the correct path of action would be to harden all parts of Bats that go into `bats-gather-tests` against this kind of interference. This is why `bats-gather-tests` has been extracted in the first place, to reduce the surface where free test code and Bats internals might interact.
